import type { Project } from '../types'

export const projects: Project[] = [
  {
    id: 1,
    titleKey: 'projects.items.defi.title',
    descriptionKey: 'projects.items.defi.description',
    tags: ['Kotlin', 'WalletConnect', 'Web3'],
    techStackKeys: [
      'kotlin',
      'java',
      'walletConnect',
      'postgres',
      'mongodb',
      'redis',
      'docker',
      'kubernetes',
    ],
    type: 'featured',
    image: '/projects-images/crypto-wallet.webp',
    caseStudyKey: 'projects.items.defi.caseStudy',
  },
  {
    id: 2,
    titleKey: 'projects.items.neural.title',
    descriptionKey: 'projects.items.neural.description',
    tags: ['Swift', 'iOS', 'AWS'],
    techStackKeys: [
      'swift',
      'uikit',
      'nodejs',
      'nestjs',
      'typescript',
      'postgres',
      'redis',
      'mongodb',
      'kafka',
      'aws',
    ],
    categoryKey: 'projects.items.neural.category',
    type: 'featured',
    image: '/projects-images/restaurant-delivery-app.webp',
    caseStudyKey: 'projects.items.neural.caseStudy',
  },
  {
    id: 3,
    titleKey: 'projects.items.saas.title',
    descriptionKey: 'projects.items.saas.description',
    tags: ['Rust', 'TUI', 'Automation'],
    techStackKeys: [
      'rust',
      'postgres',
      'kafka',
      'redis',
      'docker',
      'kubernetes',
    ],
    type: 'featured',
    image: '/projects-images/rust-terminal-social.webp',
    caseStudyKey: 'projects.items.saas.caseStudy',
  },
]
