import type { Service } from '../types'

export const services: Service[] = [
  {
    id: 'custom-software',
    icon: 'deployed_code',
    size: 'large',
    colSpan: 2,
    rowSpan: 2,
  },
  {
    id: 'legacy-migration',
    icon: 'system_update_alt',
    size: 'medium',
    colSpan: 1,
    rowSpan: 2,
    features: [
      'Zero Downtime',
      'Rollback Strategy',
      'Cost Optimization',
      'Performance Gains',
      'Technical Debt Reduction',
    ],
  },
  {
    id: 'multi-platform',
    icon: 'devices',
    size: 'medium',
    colSpan: 1,
    rowSpan: 2,
    platforms: ['iOS', 'Android', 'Web', 'Windows'],
  },
  {
    id: 'ai-integration',
    icon: 'psychology',
    size: 'small',
    colSpan: 1,
    rowSpan: 1,
    variant: 'ai',
    platforms: [
      'OpenAI',
      'Claude',
      'Gemini',
      'Mistral',
      'Ollama',
      'Grok',
      'DeepSeek',
      'Qwen',
      'MiniMax',
      'HuggingFace',
      'MCP',
    ],
  },
  {
    id: 'ux-ui-design',
    icon: 'design_services',
    size: 'small',
    colSpan: 1,
    rowSpan: 1,
    gifImage: '/gif/audio.webp',
  },
  {
    id: 'landing-pages',
    icon: 'web',
    size: 'small',
    colSpan: 2,
    rowSpan: 1,
    features: [
      'conversion_path:Conversion',
      'analytics:Analytics',
      'speed:Low LCP',
      'search:SEO-ready',
      'accessibility:Accessible',
      'language:Multi-language',
      'devices:Responsive',
      'animation:Animations',
      'security:Secure',
      'hub:Integrations',
    ],
  },
]
